### ISSUE TITLE
H36ProjectMeta not found!

### ISSUE THREAD

**Issue by JincanDeng** [xingyizhou/pose-hg-3d#6]
When I running h36mPreprocessing.m to preprocess the data, an error arises. 
Matlab tell me that H36ProjectMeta is not defined.
And I couldn't find this function anywhere.
Can you tell me how to solve this question?
Thanks!

**Comment by xingyizhou** [comment]
Hi Jincan, 
  I haven't published the data-preprocessing code, due to that this part of code is shared by other researchers and run in an old version of matlab and I didn't find time to fully re-produce them. I have  published the result of running the data pre-processing, you can refer to the link in the repo to re-produce the results in this paper. If you have any specific questions regarding to the data pro-processing, you can ask here.
